name: Release

on:
  workflow_run:
    workflows: ["Test the package"]
    branches: [main]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: GregorLueg/personal-actions/.github/workflows/rust-release.yml@v1
    with:
      publish-args: '--features hdf5-static'
    secrets: inherit

  binaries:
    needs: release
    uses: GregorLueg/personal-actions/.github/workflows/rust-binary-release.yml@v1
    with:
      binary: splatter-sc
      build-args: '--features hdf5-static'
      windows: false
    secrets: inherit
